# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=250)),
                ('imageType', models.CharField(max_length=10)),
                ('imageLink', models.CharField(max_length=1000)),
            ],
        ),
    ]
