# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-05 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessing', '0007_auto_20171230_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='documents/'),
        ),
    ]
