# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-09 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessing', '0009_auto_20180105_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrystalMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('mask', models.ImageField(upload_to='masks/')),
                ('image', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='imageProcessing.UploadedImage')),
            ],
        ),
    ]
