# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-09 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessing', '0010_crystalmask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crystalmask',
            name='mask',
        ),
        migrations.AddField(
            model_name='crystalmask',
            name='mask_dir',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
