# version: '3'

# services:
#   db:
#     image: postgres:10.1-alpine
#   web:
#     build: .
#     command: python3 manage.py migrate --noinput
#     command: python3 manage.py runserver 0.0.0.0:8888
#     ports:
#       - "8888:8888"
#     depends_on:
#       - db
version: '3'

services:
  db:
    image: postgres:10.1-alpine
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db