# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-06 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImage', '0003_auto_20180406_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
