# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-05 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imageProcessing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crystal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('crystal', models.ImageField(null=True, upload_to='crystals/')),
                ('mask', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='imageProcessing.CrystalMask')),
            ],
        ),
        migrations.CreateModel(
            name='Histogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hist_area', models.IntegerField(blank=True)),
                ('num_pair', models.IntegerField(blank=True)),
                ('overall_sim', models.IntegerField(blank=True)),
                ('crystal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crystalManagement.Crystal')),
            ],
        ),
    ]
