# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 12:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imageProcessing', '0002_auto_20180227_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crystal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('crystal_dir', models.CharField(blank=True, max_length=255)),
                ('mask', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='imageProcessing.CrystalMask')),
            ],
        ),
        migrations.CreateModel(
            name='Histogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hist_x', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=256)),
                ('hist_y', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=256)),
                ('similarities', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), size=None)),
                ('hist_area', models.IntegerField(blank=True)),
                ('num_pair', models.IntegerField(blank=True)),
                ('overall_sim', models.IntegerField(blank=True)),
                ('crystal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crystalManagement.Crystal')),
            ],
        ),
    ]
