# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystalManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crystal',
            name='dir',
        ),
        migrations.AddField(
            model_name='crystal',
            name='crystal',
            field=models.ImageField(null=True, upload_to='crystals/'),
        ),
    ]
