# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-06 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystalManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystal',
            name='pixel_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='crystal',
            name='real_area',
            field=models.IntegerField(null=True),
        ),
    ]
