# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crystalManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crystal',
            old_name='crystal_dir',
            new_name='dir',
        ),
    ]
