# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-04 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystalManagement', '0002_auto_20180406_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystal',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='crystal',
            name='mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='crystal',
            name='standard_deviation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='crystal',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
