# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-05 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystalManagement', '0003_auto_20180704_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystal',
            name='mean',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='crystal',
            name='standard_deviation',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
