# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-05 15:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploadImage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrystalMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.ImageField(null=True, upload_to='masks/')),
                ('name', models.CharField(default='no name', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uploadImage.UploadedImage')),
            ],
        ),
        migrations.CreateModel(
            name='TempImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='temp_images/')),
                ('thumbnail', models.ImageField(null=True, upload_to='temp_thumbnails/')),
                ('func_name', models.CharField(blank=True, max_length=255, null=True)),
                ('func_setting', models.CharField(blank=True, max_length=255, null=True)),
                ('gray_levels', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('k_labels', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='TempMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.ImageField(null=True, upload_to='temp_masks/')),
            ],
        ),
        migrations.AddField(
            model_name='tempimage',
            name='mask',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='imageProcessing.TempMask'),
        ),
    ]
