# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 17:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrystalMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('mask_dir', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TempImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='temp_images/')),
                ('thumbnail', models.ImageField(null=True, upload_to='temp_thumbnails/')),
                ('func_name', models.CharField(blank=True, max_length=255, null=True)),
                ('func_setting', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.ImageField(null=True, upload_to='temp_masks/')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('thumbnail', models.ImageField(null=True, upload_to='thumbnails/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tempimage',
            name='mask',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='imageProcessing.TempMask'),
        ),
        migrations.AddField(
            model_name='crystalmask',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='imageProcessing.UploadedImage'),
        ),
    ]
