# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-06 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystalmask',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 6, 9, 33, 41, 251346, tzinfo=utc)),
        ),
    ]
