# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-27 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumberInput',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
