# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 18:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessing', '0002_auto_20180307_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempimage',
            name='gray_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='tempimage',
            name='k_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None),
        ),
    ]
