# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-05 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessing', '0003_tempimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempimage',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='temp_thumbnails/'),
        ),
    ]
