# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-08 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessing', '0003_auto_20180406_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystalmask',
            name='cluster',
            field=models.FileField(null=True, upload_to='csv/'),
        ),
    ]
