# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-06 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessing', '0004_tempimage_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='document',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/'),
        ),
    ]
