# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageProcessing', '0005_auto_20180308_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crystalmask',
            name='mask_dir',
        ),
        migrations.AddField(
            model_name='crystalmask',
            name='mask',
            field=models.ImageField(null=True, upload_to='masks/'),
        ),
    ]
